### ISSUE TITLE
能制作一个库吗？

### ISSUE THREAD

**Issue by saltwater2233** [wbzlop/Scanner#1]
引用起来比较麻烦，希望能导一个三方库

**Comment by wbzlop** [comment]
最近去忙其他项目了，没时间继续整理。其实只是在[SmartCropper](https://github.com/pqpo/SmartCropper)基础上修改识别部分。

**Comment by saltwater2233** [comment]
@wbzlop 
在SmartCropper的CropImageView里没有发现setImageToCrop(bitmap, output)这个方法，能麻烦你把CropImageView也上传吗

hedDetect.run(bitmap, new HEDDetect.HEDDetectAction() {
                @Override
                public void complete(float[] output) {
                    mCropImageView.setImageToCrop(bitmap, output);
                }
            });

**Comment by wbzlop** [comment]
只是修改原setImageToCrop接口，多了个参数，然后替换扫点方法
Point[] scan = SmartCropper.hedScan(output, bitmap.getWidth(), bitmap.getHeight());
